apiVersion: jenkins.io/v1
kind: Environment
metadata:
  annotations:
    jenkins.io/chart: env
  labels:
    jenkins.io/chart-release: jenkins-x
    jenkins.io/namespace: jx
    jenkins.io/version: "1"
  name: staging
spec:
  kind: Permanent
  label: Staging
  namespace: jx-staging
  order: 100
  previewGitInfo:
    user: {}
  promotionStrategy: Auto
  remote: false
  source:
    ref: master
    url: https://github.com/myorg/environment-mycluster-staging.git
